include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false


linter:
  rules:
   - always_put_control_body_on_new_line
   - curly_braces_in_flow_control_structures
   - unnecessary_new
   - avoid_relative_lib_imports
   - directives_ordering
   - file_names
   - prefer_collection_literals
   - prefer_single_quotes
   - prefer_final_fields
   - prefer_final_locals
   - annotate_overrides